config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :experiences, only: [:create, :update, :destroy]
  resources :organizations, only: [:create, :destroy]
  post 'coforg', to: 'organizations#createorfind'
  resources :applies do
    resources :organizations, only: [ :edit, :update]
    member do
      patch "/change_status", to:'applies#change_status'
      patch "/accept", to:'applies#accept'
      patch "/decline", to:'applies#decline'
    end
    resources :notification_applies, only: [:create] do
      patch "/change_read_apply", to: 'applies#change_read_apply', as: :change_apply
    end
    resources :notification_interviews, only: [:create] do
      patch "/change_read_interview", to: 'applies#change_read_interview', as: :change_int
    end
    resources :contacts, only: [:create, :update, :destroy]
    resources :interviews, only: [:create, :update, :destroy] do
      resources :reviews, only: [:create, :update, :destroy] do
        patch "/upvote", to:"reviews#upvote"
        patch "/downvote", to:"reviews#downvote"
      end
    end
  end
  resources :votes, only: [:create, :update, :destroy]
  resources :articles, only: [:index, :show]
  get 'myprofile', to: 'pages#profile', as: :profile

end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  belongs_to :organization
  has_many :contact_applies
  has_many :contacts, through: :contact_applies, dependent: :destroy
  has_many :interviews, dependent: :destroy
  has_many :reviews, through: :interview
  has_many :notification_applies, dependent: :destroy
  has_many :notification_interviews, through: :interview
  validates :job_title, presence: true
  validates :status, presence: true, inclusion: { in: %w(Ready\ to\ apply Applied Ongoing\ process Waiting\ for\ answer),
    message: "%{value} is not a valid" }
  validates :finalstatus, inclusion: { in: %w(Pending Accepted Declined) }
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
   before_action :set_apply, only: [:show,:edit,:update,:destroy]

  def index
    @applies = policy_scope(Apply).order(created_at: :desc)
    @apply = Apply.new
  end

  def show
    authorize @apply
    @interview = Interview.new
    @contact = Contact.new
    @review = Review.new
    @reviews = Review.all.order("votes DESC")
  end

  def create
    @apply = Apply.new(apply_params)
    authorize @apply
    @organization = Organization.find_by(name: params[:apply][:organization])
    @apply.organization = @organization
    @apply.user = current_user
    if @apply.save
      redirect_to apply_path(@apply)
    else
      redirect_to applies_path
    end
  end

  def edit
    authorize @apply
  end

  def update
    @apply.update(apply_params)
    redirect_to applies_path
    authorize @apply
  end

  def destroy
    @apply.destroy
    redirect_to applies_path
    authorize @apply
  end

  def change_status
    @apply = Apply.find(params[:id])
    a = ["Ready to apply", "Applied", "Ongoing process", "Waiting for answer"]
    if a.index(@apply.status) == 0
      @apply.status = a[1]
    elsif a.index(@apply.status) == 1
      @apply.status = a[2]
    elsif a.index(@apply.status) == 2
      @apply.status = a[3]
    else
      @apply.status = a[2]
    end
    @apply.updatedate = Date.today()
    @apply.save
    redirect_to applies_path, notice: "status changed"
    authorize @apply
  end

  def accept
    @apply = Apply.find(params[:id])
    @apply.finalstatus = "Accepted"
    @apply.save
    redirect_to applies_path, notice: "Well done ! 🚀"
    authorize @apply
  end

  def decline
    @apply = Apply.find(params[:id])
    @apply.finalstatus = "Declined"
    @apply.save
    redirect_to applies_path, notice: "Keep doing ! 💪"
    authorize @apply
  end

  def change_read_apply
      @notification_apply = NotificationApply.find(params[:notification_apply_id])
      @notification_apply.read = true
      redirect_to apply_path(@notification_apply.apply)
      authorize @notification_apply
      @notification_apply.save!
  end

  def change_read_interview

      @notification_interview = NotificationInterview.find(params[:notification_interview_id])
      @notification_interview.read = true
      redirect_to apply_path(@notification_interview.interview.apply)
      authorize @notification_interview
      @notification_interview.save!
  end

  def upvote

  end


  private

  def set_apply
    @apply = Apply.find(params[:id])
  end

  def apply_params
    params.require(:apply).permit(:job_title, :description, :status, :progression_bar, :location, :ranking, :url, :organization_id, :finalstatus)
  end

end

app/views/applies/index.html.erb
<div class="row-application">
  <div class="one">
      <div class="calendar">
        <h3>Calendar</h3>
        <p id = "today"></p>
        <hr>
        <div class="month">
          <div>
            <i class="fas fa-angle-left prev"></i>
          </div>
          <div class="date">
            <p id = "month"></p>
          </div>
          <div>
            <i class="fas fa-angle-right next"></i>
          </div>
        </div>
        <div class="weekdays">
          <div>Sun</div>
          <div>Mon</div>
          <div>Tue</div>
          <div>Wed</div>
          <div>Thu</div>
          <div>Fri</div>
          <div>Sat</div>
        </div>
        <div class="days"></div>
      </div>
    <div class="dashboard">
      <h3>Statistics</h3>
      <h5>You have <%= Apply.where(user_id: current_user).where(finalstatus: "Pending").count %> applications</h5>
      <hr>
      <%= pie_chart Apply.where(user_id: current_user).where(finalstatus: "Pending").group(:status).count, colors: ["#E85F5C", "#071422", "#81AE9D", "#736CED"], donut: true %>
      <hr>
      <%= area_chart Apply.where(user_id: current_user).group_by_day(:created_at).count, colors: ["#E85F5C"], title: "Applications per day" %>
    </div>
  </div>
   <div class="two">
    <h3 class="applications-title">My applications</h3>
    <div class = "filter">
        <div class="category-filters">
          <div class="category-btn ready"  data-filter= "Ready" >
            Ready to apply
          </div>
          <div class="category-btn applied" data-filter= "Applied">
            Applied
          </div>
          <div class="category-btn ongoing" data-filter= "Ongoing" >
            Ongoing process
          </div>
          <div class="category-btn waiting" data-filter= "Waiting">
            Waiting for answer
          </div>
        </div>
    </div>

    <div class="filter-add">
      <a class="filter-plus" data-toggle="modal" data-target="#AddApply" ><i class="fas fa-plus-circle"></i></a>
    </div>


    <% if current_user.applies.count === 0 %>
      <p> You don't have any applications yet <p>
    <% else %>

      <div class="card-application-active">
         <% @applies.each do |apply|%>
            <% if current_user.id === apply.user_id && apply.finalstatus === "Pending" %>
              <%= link_to apply_path(apply) do %>
                <div class="card-application" data-filter=<%= apply.status %>>
                <div class= "card-application-left" >
                  <img src=<%=apply.organization.logo%> class="card-application-img" />


                  <div class="card-application-infos">
                    <p><%=apply.job_title.capitalize%></p>
                    <p id="organization-name"><%=apply.organization.name%></p>
                    <% if apply.location.blank?  %>

                    <% else %>
                      <p><small><i class="fas fa-map-marker-alt"></i>  <%=apply.location.gsub(/,.*,/, ', ')%></small></p>
                    <% end %>
                  </div>

                 <div class="step">
                  <% if apply.interviews.size == 0 %>
                    <p>No interview planned </p>
                  <% else %>
                    <p class="itwselector" data-date="<%= apply.interviews.last.date.strftime("%Y-%-m-%-d")%>"><%=apply.interviews.last.step%></p>
                  <% end %>
                 </div>

                <div class="status">
                  <% if apply.status === "Ready to apply"  %>
                    <p id="status-ready"><%= apply.status %></p>
                  <%elsif apply.status === "Applied"  %>
                    <p id="status-applied"><%= apply.status %></p>
                  <%elsif apply.status === "Ongoing process"  %>
                    <p id="status-ongoing"><%= apply.status %></p>
                  <%else%>
                    <p id="status-waiting"><%= apply.status %></p>
                  <% end %>
                </div>

              </div>
              <%=link_to change_status_apply_path(apply), method: :patch do %>
              <div class="arrow-wrapper">
                <%= link_to ('<i class="fas fa-level-up-alt"></i>').html_safe, change_status_apply_path(apply), method: :patch,
                data: {confirm:"Are you sure you want to update the status of your application to #{
                if apply.status === "Ready to apply"
                  "Applied"
                elsif apply.status === "Applied"
                  "Ongoing process"
                elsif apply.status === "Ongoing process"
                  "Waiting for answer"
                else
                  "Ongoing process"
                end } ?"},
                :title => "Update to #{
                if apply.status === "Ready to apply"
                  "Applied"
                elsif apply.status === "Applied"
                  "Ongoing process"
                elsif apply.status === "Ongoing process"
                  "Waiting for answer"
                else
                  "Ongoing process"
                end
              }"%>
                <a class="btn p-0 acceptedbtn" data-toggle="modal" data-target="#AnimationAccept" id="animationAccept" data-acceptid="<%=apply.id%>" ><i class="far fa-check-circle"></i></a>
                <%= render 'shared/animationaccept', apply: apply, display_modal: @display_modal %>
                <a class="btn p-0 declinedbtn" data-toggle="modal" data-target="#AnimationReject" id="animationreject" data-declineid="<%=apply.id%>"><i class="fas fa-trash-alt"></i></a>
                <%= render 'shared/animationreject', apply: apply, display_modal: @display_modal %>
              </div>
            <% end %>
          
          </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

<button id="hide">Archives</button>

<div id="myDIV">
  <% @applies.each do |apply|%>
    <% if current_user.id === apply.user_id && apply.finalstatus === "Accepted" %>
      <%= link_to apply_path(apply)do %>

      <div class="card-application-archive-accepted" data-filter=<%= apply.status %>>
        <div class= "card-application-left" >
          <img src=<%=apply.organization.logo%> class="card-application-img" />
          <div class="card-application-infos">
           <p><%=apply.job_title.capitalize%></p>
           <p id="organization-name"><%=apply.organization.name%></p>
          <% if apply.location.blank?  %>

          <% else %>
            <p><small><i class="fas fa-map-marker-alt"></i>  <%=apply.location%></small></p>
          <% end %>
        </div>
        <div class="step">
          <% if apply.interviews.size == 0 %>
            <p>No interview planned </p>
          <% else %>
            <p><%=apply.interviews.last.step%></p>
          <% end %>
        </div>
        <div class="status">
          <% if apply.status === "Ready to apply"  %>
            <p id="status-ready"><%= apply.status %></p>
          <%elsif apply.status === "Applied"  %>
            <p id="status-applied"><%= apply.status %></p>
          <%elsif apply.status === "Ongoing process"  %>
            <p id="status-ongoing"><%= apply.status %></p>
          <%else%>
            <p id="status-waiting"><%= apply.status %></p>
          <% end %>
        </div>
        <div id="Accepted">
          <p> Job Offer <p>
        </div>
      </div>
    </div>
    <% end %>

      <% elsif current_user.id === apply.user_id && apply.finalstatus === "Declined" %>
        <%= link_to apply_path(apply)do %>
          <div class="card-application-archive-declined" data-filter=<%= apply.status %>>
                    <div class= "card-application-left" >
          <img src=<%=apply.organization.logo%> class="card-application-img" />
          <div class="card-application-infos">
           <p><%=apply.job_title.capitalize%></p>
           <p id="organization-name"><%=apply.organization.name%></p>
          <% if apply.location.blank?  %>

          <% else %>
            <p><small><i class="fas fa-map-marker-alt"></i>  <%=apply.location%></small></p>
          <% end %>
        </div>
        <div class="step">
          <% if apply.interviews.size == 0 %>
            <p>No interview planned </p>
          <% else %>
            <p><%=apply.interviews.last.step%></p>
          <% end %>
        </div>
        <div class="status">
          <% if apply.status === "Ready to apply"  %>
            <p id="status-ready"><%= apply.status %></p>
          <%elsif apply.status === "Applied"  %>
            <p id="status-applied"><%= apply.status %></p>
          <%elsif apply.status === "Ongoing process"  %>
            <p id="status-ongoing"><%= apply.status %></p>
          <%else%>
            <p id="status-waiting"><%= apply.status %></p>
          <% end %>
        </div>
        <div id="Declined">
          <p> No Job Offer <p>
        </div>
      </div>
          </div>
      <% end %>

    <% end %>
  <% end %>
</div>
   </div>
  </div>


     <%= render 'shared/new_apply_modal', apply: @apply, display_modal: @display_modal %>

app/views/applies/show.html.erb
<div class="row-application justify-content-around">
  <div class="one">
    <div class="calendar" id="show-calendar">
        <h3>Calendar</h3>
        <p id = "today"></p>
        <hr>
        <div class="month">
          <div>
            <i class="fas fa-angle-left prev"></i>
          </div>
          <div class="date">
            <p id = "month"></p>
          </div>
          <div>
            <i class="fas fa-angle-right next"></i>
          </div>
        </div>
        <div class="weekdays">
          <div>Sun</div>
          <div>Mon</div>
          <div>Tue</div>
          <div>Wed</div>
          <div>Thu</div>
          <div>Fri</div>
          <div>Sat</div>
        </div>
        <div class="days"></div>
      </div>
    </div>
  <div class="application-details">
    <div class="text-center d-flex">
      <div>
        <img src=<%=@apply.organization.logo%> class="logo-show" />
      </div>
      <div class="flex-grow-1 text-left title-company">
      <div class= "d-flex align-items-baseline " style="    width: 90%;">
      <h3><%= @apply.organization.name %> - <%= @apply.job_title.capitalize %></h3>

     <div class="px-3">
       <% if @apply.location.blank?  %>

                    <% else %>
                      <p><small><i class="fas fa-map-marker-alt"></i>  <%=@apply.location.gsub(/,.*,/, ', ')%></small></p>
                    <% end %>
                    </div>
       </div>
        <hr style="width: 90%; margin-left:0">
        <%= link_to ('<i class="far fa-times-circle"></i>').html_safe, applies_path %>
        <%= link_to edit_apply_organization_path(@apply,@apply.organization) do %>
        <span class="btn button-cta edit-apply ">Edit</span>
        <%end  %>
        <span class="status-show">
         <% if @apply.finalstatus == "Accepted" %>
         <p class="text-right"><small>Job offer: <i class="fas fa-check"></i></small></p>

         <% elsif @apply.finalstatus == "Declined" %>
        <p class="text-right"><small>Job offer: <i class="fas fa-minus-circle"></i></small></p>
          <% elsif @apply.status === "Ready to apply"  %>
            <p id="status-ready"><%= @apply.status %></p>
          <%elsif @apply.status === "Applied"  %>
            <p id="status-applied"><%= @apply.status %></p>
          <%elsif @apply.status === "Ongoing process"  %>
            <p id="status-ongoing"><%= @apply.status %></p>
          <%else%>
            <p id="status-waiting"><%= @apply.status %></p>
          <% end %>
        </span>
      </div>
    </div>
      <div class="text-center ">
        <div class="interviews justify-content-around">
          <div class="d-flex">
            <%if @apply.interviews.count > 0  %>
            <% @apply.interviews.each do |interview| %>
              <span class="btn interview_button itwselector" data-description="<%=interview.notes%>" 
              data-itwid="<%=interview.id%>" data-applyid="<%=@apply.id%>"
              data-date="<%= interview.date.strftime("%Y-%-m-%-d")%>" data-start_time="<%=interview.start_time.strftime("%I:%M")%>" data-end_time="<%= interview.end_time.strftime("%I:%M")%>"><%= interview.step %></span>
            <% end %>
            <%else %>
            <p><em>You have no interviews planned yet !</em></p>
             <%end%>
          </div>
        <div>
        <%if @apply.interviews.count > 0  %>
        <a class="btn" data-toggle="modal" data-target="#ReviewModal" id="additw" ><i class="fas fa-plus-circle"></i></a>
         <%else  %>
       <a class="btn" data-toggle="modal" data-target="#ItwModal" id="additw" ><i class="fas fa-plus-circle"></i></a>
       <%end%>    
      </div>
        </div>
      </div>

<div id='grow'>
  <div class='measuringWrapper'>
        <div class="card-interview" id="itwcard" style="display: none">
  
      </div>
    </div>
</div>
   <hr style="width: 60%">
      <%# <hr style="width: 60%"> %>
      <div class="company-details">
        <div class="d-flex justify-content-between me-2">
        <h6>Company description</h6>
        <%unless  @apply.organization.category.nil? %>
         <h6>Category: <%=@apply.organization.category  %></h6>
           <%end  %>
         </div>
     
        <p><%= @apply.organization.description %> </p>
      </div>
      <hr style="width: 60%">
      <div class="company-details">
        <h6>Offer details</h6>
        <p> <%= @apply.description %></p>
      </div>
      <hr style="width: 60%">
      <div class="contacts-apply">
        <h6>My contacts</h6>
        <% if @apply.contacts.count > 0  %>
          <div class="contacts d-flex justify-content-between">
            <div>
            <% @apply.contacts.each do |contact| %>
            <%= link_to contact.linkedin_url, target: :_blank, title: contact.name do %>
              <% if contact.photo.attached? %>
                <%= cl_image_tag(contact.photo.key, class:"avatar-small") %>
              <% else %>
                <%= cl_image_tag("qsdgkammqm7nwczbuagw", class:"avatar-small") %>
              <% end %>
            <% end %>
            <% end  %>

            </div>
            <div>
            <a class="btn" data-toggle="modal" data-target="#ContactModal" id="addcontact" ><i class="fas fa-plus-circle"></i></a>
            </div>
          </div>
          <% else %>
          <div class="contacts d-flex justify-content-between">
            <div>
            <p><em>You have no contacts for the moment, it's time to add one !</em></p>
            </div>
            <div>
            <a class="btn" data-toggle="modal" data-target="#ContactModal" id="addcontact" ><i class="fas fa-plus-circle"></i></a>
            </div>
          </div>
        <% end  %>
      </div>
      <hr style="width: 60%">
      <div class="review-details">

         <h6>Reviews</h6>
      </div>
      <div>
        <% @reviews.each do |review| %>
          <% if @apply.organization.name == review.interview.apply.organization.name %>
            <div class="reviews">
              <div class="review-person">
                <% if review.interview.apply.user.photo.attached? %>
                  <%= cl_image_tag(review.interview.apply.user.photo.key, class:"avatar-large") %>
                <% else %>
                  <%= cl_image_tag("qsdgkammqm7nwczbuagw", class:"avatar-large") %>
                <% end %>
                <p><strong><%= review.interview.apply.user.first_name %> <%= review.interview.apply.user.last_name.first %>.</strong></p>
                <p><small class="date"><%=review.interview.date%></small></p>
              </div>
              <div class="reviews-content">
                  <h6><strong><%= review.interview.step %> for <%= review.interview.apply.job_title %></strong></h6>
                  <% if review.interview.apply.finalstatus == "Pending" %>
                    <p><small>Job offer: <i class="far fa-clock"></i></small></p>
                  <% end %>
                  <% if review.interview.apply.finalstatus == "Accepted" %>
                    <p><small>Job offer: <i class="fas fa-check"></i></small></p>
                  <% end %>
                  <% if review.interview.apply.finalstatus == "Declined" %>
                    <p><small>Job offer: <i class="fas fa-minus-circle"></i></small></p>
                  <% end %>
              <p><%=review.comment%></p>
              </div>
            <p><%=review.rating%>/10</p>
            <div class ="votes">
            <%= link_to apply_interview_review_upvote_path(review.interview.apply, review.interview, review), method: :patch, remote: true do  %>

            <i class=" btn fas fa-chevron-up arrow-vote upvote" data-review-id="<%=review.id%>"  >  </i>
            <%end  %>


	        	<span class="count"id ="countvote-<%=review.id%>"><%=review.votes%></span>

            <%= link_to apply_interview_review_downvote_path(review.interview.apply, review.interview, review), method: :patch, remote: true do  %>
            <i class="btn fas fa-chevron-down arrow-vote downvote" data-review-id="<%=review.id%>"r>  </i>
            <% end  %>

</div>
            </div>
          <% end %>
       <% end %>
      </div>
    </div>
  </div>
</div>

<!--Interview Modal -->

    <%= render 'shared/review_modal', interview: @interview, apply: @apply, review: @review %>
    <%= render 'shared/itw_modal', interview: @interview, apply: @apply %>

<!-- Contact Modal -->

   <%= render 'shared/contact_modal',contact: @contact, apply: @apply%>
   <%= render 'shared/edit_itw_modal', apply: @apply %>