config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :experiences, only: [:create, :update, :destroy]
  resources :organizations, only: [:create, :destroy]
  post 'coforg', to: 'organizations#createorfind'
  resources :applies do
    resources :organizations, only: [ :edit, :update]
    member do
      patch "/change_status", to:'applies#change_status'
      patch "/accept", to:'applies#accept'
      patch "/decline", to:'applies#decline'
    end
    resources :notification_applies, only: [:create] do
      patch "/change_read_apply", to: 'applies#change_read_apply', as: :change_apply
    end
    resources :notification_interviews, only: [:create] do
      patch "/change_read_interview", to: 'applies#change_read_interview', as: :change_int
    end
    resources :contacts, only: [:create, :update, :destroy]
    resources :interviews, only: [:create, :update, :destroy] do
      resources :reviews, only: [:create, :update, :destroy] do
        patch "/upvote", to:"reviews#upvote"
        patch "/downvote", to:"reviews#downvote"
      end
    end
  end
  resources :votes, only: [:create, :update, :destroy]
  resources :articles, only: [:index, :show]
  get 'myprofile', to: 'pages#profile', as: :profile

end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @articles = policy_scope(Article).order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
    authorize @article
  end
end

app/views/articles/index.html.erb
<div class="container">
  <h2>Find the <mark>best tips</mark> to find the best job</h2>
  <div class="article">
    <% @articles.each do |article| %>
      <%= link_to article_path(article) do%>
        <div class="card-article">
          <%= image_tag "https://images.unsplash.com/photo-1621570359164-ad2429a2c93b?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80" %>
          <div class="card-article-infos">
            <h2><%= article.tile %></h2>
            <p><%= article.author %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="my-5 text-center">
    <%= link_to "Go back to homepage", root_path, class:"btn button-classic" %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="blog-banner">
  <h2><%= @article.tile %></h2>
</div>

<div class="container">
  <div>
    <%= link_to "< See all articles", articles_path, class:"btn button-back" %>
  </div>
  <p><em>By <%=@article.author %></em></p>
  <p><%= @article.content %></p>
  <div class="my-5 text-center">
    <%= link_to "Go back to homepage", root_path, class:"btn button-classic" %>
  </div>
</div>