config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :experiences, only: [:create, :update, :destroy]
  resources :organizations, only: [:create, :destroy]
  post 'coforg', to: 'organizations#createorfind'
  resources :applies do
    resources :organizations, only: [ :edit, :update]
    member do
      patch "/change_status", to:'applies#change_status'
      patch "/accept", to:'applies#accept'
      patch "/decline", to:'applies#decline'
    end
    resources :notification_applies, only: [:create] do
      patch "/change_read_apply", to: 'applies#change_read_apply', as: :change_apply
    end
    resources :notification_interviews, only: [:create] do
      patch "/change_read_interview", to: 'applies#change_read_interview', as: :change_int
    end
    resources :contacts, only: [:create, :update, :destroy]
    resources :interviews, only: [:create, :update, :destroy] do
      resources :reviews, only: [:create, :update, :destroy] do
        patch "/upvote", to:"reviews#upvote"
        patch "/downvote", to:"reviews#downvote"
      end
    end
  end
  resources :votes, only: [:create, :update, :destroy]
  resources :articles, only: [:index, :show]
  get 'myprofile', to: 'pages#profile', as: :profile

end

app/views/shared/_contact_modal.html.erb
<div class="modal fade" id="ContactModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a contact</h5>
         <%=link_to  apply_path(apply), class:"quitmodal" do %>
        <i class="fas fa-times "></i>
          <%end %>
      </div>
              <%= simple_form_for([apply, contact]) do |f| %>

      <div class="modal-body">
      <hr>

      <%= f.input :name, as: :string, input_html: { autocomplete: 'off'  }%>

      <%= f.input :linkedin_url, as: :string %>
      <%= f.input :photo, as: :file%>
      </div>
      <div class="modal-footer">
           <%= f.button :submit, "Add", class: "btn button-cta"%>
      </div>
    <% end %>
    </div>
  </div>

</div>

app/views/shared/_edit_itw_modal.html.erb
<div class="modal fade" id="EditItwModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit my notes</h5>
         <%=link_to apply_path(apply), class:"quitmodal" do %>
        <i class="fas fa-times "></i>
          <%  end %>
      </div>
      <div class="simpleformid">
              
      </div>
    </div>
  </div>

</div>

app/views/shared/_experience_modal.html.erb
<div class="modal fade" id="ExperienceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document" data-display="<%=display_modal_exp ? "show_exp" : "none" %>">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add an experience</h5>
        <%=link_to  profile_path, class:"quitmodal" do %>
        <i class="fas fa-times "></i>
          <%end %>
      </div>
        <%= simple_form_for experience do |f| %>

      <div class="modal-body">
      <%= f.input :organization, input_html: { id: 'companysearch', autocomplete: 'off'  } %>
      <div class="list-group" id="companyresults">
       </div>
        <hr>
          <div class="mb-3">
         <p>Start Date</p>
         <%= f.date_select :start_date,  { :discard_day => true}, {:class => "dateexp"}   %>
         </div>
            <div class="mb-3">
            <p>End Date</p>
            <%= f.date_select :end_date,   { :discard_day => true}, {:class => "dateexp"}   %>
            </div>

      <%= f.input :description, as: :text, placeholder: 'Enter a description of what you\'ve done there...', input_html: { autocomplete: 'off'  }%>
      <%= f.input :location, as: :string, input_html: { id: 'address2', autocomplete: 'off' }, placeholder: 'Enter the location of your job...'%>
      <%= f.input :category, input_html: { :value => "work"}, as: :hidden %>



      </div>

      <div class="modal-footer">
           <%= f.button :submit, "Add", class: "btn button-cta"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/thomassdug/jobin" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/welcometothejunglestudents/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.linkedin.com/company/glassdoor/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-contactus">
    Send us an email to improve <strong>jobin</strong>: <a href = "mailto: contact@jobin.work" class="email-btn">contact@jobin.work</a>
  </div>
  <div class="footer-copyright">
     Made with <i class="fas fa-heart"></i> by Grégoire, Maxence, Venkatesh & Thomas
  </div>
</div>

app/views/shared/_itw_modal.html.erb
<div class="modal fade" id="ItwModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add an interview</h5>
        <%=link_to  apply_path(apply), class:"quitmodal" do %>
        <i class="fas fa-times "></i>
          <%end %>
      </div>
              <%= simple_form_for([apply, interview]) do |f| %>

      <div class="modal-body">
      <%= f.input :date, as: :string, input_html: {id: "date"}  %>
      <%= f.input :start_time, as: :string, input_html: {class: 'houritw hour' }%>
      <%= f.input :end_time, as: :string, input_html: {class: 'houritw hour' }  %>
      <%= f.input :step, as: :string, placeholder: 'Enter the step of your upcoming interview...', input_html: { autocomplete: 'off'  }%>
      <%= f.input :notes, as: :text, placeholder: 'Enter notes, if you have some...', input_html: { autocomplete: 'off'  }%>
      </div>
      <div class="modal-footer">
           <%= f.button :submit, "Add", class: "btn button-cta"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-jobin">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/png/512/3135/3135680.png" %>
    <%= " | jobin" %>
  <% end %>
    <div>
      <ul class="navbar-nav mr-auto" id="indextoactive">
        <% if user_signed_in? %>
           <li class="nav-item <%= 'active-item' if current_page?(applies_path) %>">
           <%= link_to "My Dashboard", applies_path, class: "link-nav" %>
        </li>
        <% end %>
        <li class="nav-item <%= 'active-item' if current_page?(articles_path)%>">
          <%= link_to "Articles", articles_path , class: "link-nav" %>
        </li>
      </ul>
    </div>

    <% if user_signed_in? %>
     <div class= "connexion">
      <ul class="navbar-nav mr-auto" id="indextoactive">
        <li class="nav-item dropdown">

          <i class="far fa-bell" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

           <%unless @notification_applies.nil? %>
            <%unless @notification_interviews.nil? %>
           <span class="badge"><%=@notification_applies.where(read: false).count + @notification_interviews.where(read: false).count %></span>
          <%end  %>
          <%end  %>

          <div class="dropdown-menu dropdown-menu-right dropdownnotif" aria-labelledby="navbarDropdown">
            <%unless @notification_applies.nil?   %>
            <% @notification_applies.each do |notification_apply|%>
            <% if notification_apply.read == false %>
          <%=link_to apply_notification_apply_change_apply_path(notification_apply.apply, notification_apply), class:"dropdown-item dropdown-item-notification", method: :patch do %>
            <div class= "d-flex notification-card">
            <% if notification_apply.apply.status == "Waiting for answer"  %>
            <div>
              <img src=<%=notification_apply.apply.organization.logo%> class="notification-card-img" />
               </div>
               <div class="notif-card-text">
                <p>Don't forget to contact <strong><%=notification_apply.apply.organization.name%></strong> for the <strong><%=notification_apply.apply.job_title%></strong> offer </p>
              </div>
              <% else %>
              <div>
              <img src=<%=notification_apply.apply.organization.logo%> class="notification-card-img" />
               </div>
               <div class="notif-card-text">
                <p>Don't forget to apply <strong><%=notification_apply.apply.organization.name%></strong> for the <strong><%=notification_apply.apply.job_title%></strong> offer </p>
             </div>
              <% end %>
              </div>
              <hr  class="p-0 m-0">
            <% end %>
          <% end %>
          <% end %>

          <% end  %>
        <%unless @notification_interviews.nil?   %>
          <% @notification_interviews.each do |notification_interview|%>
            <% if notification_interview.read == false %>
          <%=link_to apply_notification_interview_change_int_path(notification_interview.interview.apply, notification_interview), class:"dropdown-item dropdown-item-notification", method: :patch do %>
            <div class= "d-flex notification-card">
            <div>
              <img src=<%=notification_interview.interview.apply.organization.logo%> class="notification-card-img" />
               </div>
               <div class="notif-card-text">
                <p>Don't forget your interview with <strong><%=notification_interview.interview.apply.organization.name%></strong> for the <strong><%=notification_interview.interview.apply.job_title%></strong> offer (in <strong><%= (notification_interview.interview.date - Date.today()).ceil%> </strong> days) </p>
              </div>
              </div>
              <hr  class="p-0 m-0">
            <% end %>
          <% end %>
          <% end %>
          <% end  %>
          </div>
        </li>
      </ul>
       <div class="d-flex">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
       <% if current_user.photo.attached? %>

          <%= cl_image_tag(current_user.photo.key,  class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>

       <%else %>

          <%=  cl_image_tag("qsdgkammqm7nwczbuagw", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
           <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <h3 class= "dropdown-item">Hi, <%= current_user.first_name %></h3>
            <%= link_to "My Profile",profile_path , class: "dropdown-item" %>

            <%= link_to "Edit Profile",edit_user_registration_path , class: "dropdown-item" %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        </ul>
        </div>
      </div>

      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "btn button-cta" %>
      <% end %>
    </div>
    </div>

app/views/shared/_new_apply_modal.html.erb
<div class="modal fade" id="AddApply" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add an application</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <%= simple_form_for apply do |f| %>
      <div class="modal-body">

         <%= f.input :organization, input_html: { id: 'companysearch',autocomplete: 'off'  } %>
      <div class="list-group" id="companyresults">
</div>
        <%= f.input :job_title, as: :string, placeholder: 'Enter the position...', input_html: { autocomplete: 'off'  }%>
        <%= f.input :description, as: :text, placeholder: 'Put a short description of the job...', input_html: { autocomplete: 'off'  }%>
        <%= f.input :status, as: :radio_buttons, :collection => %w[Ready\ to\ apply Applied Ongoing\ process Waiting\ for\ answer] , input_html: { autocomplete: 'off'  }%>
        <%= f.input :location, as: :string, input_html: { id: 'address1',autocomplete: 'off'  }, placeholder: 'Enter the city...'%>
        <%= f.input :url, as: :string, placeholder: 'Enter the url of the offer...', input_html: { autocomplete: 'off'  }%>
        <%= f.input :updatedate, input_html: { :value => Date.today()}, as: :hidden %> 
      </div>

      <div class="modal-footer">
           <%= f.button :submit, "Add", class: "btn button-cta"%>
      </div>
     <% end %>
    </div>
  </div>
</div>

app/views/shared/_review_modal.html.erb
<% if apply.interviews.count >0  %>
<div class="modal fade" id="ReviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">

        <h5 class="modal-title" id="exampleModalLabel">First, add a review about : <%=apply.interviews.last.step%></h5>

       <%=link_to  apply_path(apply), class:"quitmodal" do %>
        <i class="fas fa-times "></i>
          <% end %>
      </div>
  <%= simple_form_for([apply, apply.interviews.last,review], remote: true) do |f| %>

      <div class="modal-body">

      <div class="range-wrap">
    <div class="range-value" id="rangeV"></div>
    <%= f.input :rating, as: :range, input_html: { min: 0, max: 10,step:0.5 }%>
    </div>
      
      <%= f.input :comment, as: :text, placeholder: 'Give a comment about your previous interview...'%>
      </div>

      <div class="modal-footer">
           <%= f.button :submit, "Add", class: "btn button-cta", id:"submitreview"%>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_school_modal.html.erb
<div class="modal fade" id="SchoolModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document"  data-display="<%=display_modal_school ? "show_school" : "none" %>">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add an education</h5>
        <%=link_to  profile_path, class:"quitmodal" do %>
        <i class="fas fa-times "></i>
          <%end %>
      </div>
        <%= simple_form_for experience do |f| %>

      <div class="modal-body">
     <%= f.input :organization, input_html: { id: 'schoolsearch',autocomplete: 'off'  } %>
      <div class="list-group" id="schoolresults">
</div>
         <div class="mb-3">
           <p>Start Date</p>
           <%= f.date_select :start_date,  { :discard_day => true}, {:class => "dateexp"}   %>
         </div>
           <div class="mb-3">
           <p>End Date</p>
           <%= f.date_select :end_date,   { :discard_day => true}, {:class => "dateexp"}   %>
         </div>
      <%= f.input :description, as: :text, placeholder: 'Enter a description of what you\'ve done there...', input_html: { autocomplete: 'off'  }%>
      <%= f.input :location, as: :string, input_html: { id: 'address1',autocomplete: 'off'  }, placeholder: 'Enter the location of your school...'%>
      <%= f.input :category, input_html: { :value => "school"}, as: :hidden %>

      </div>
      <div class="modal-footer">
           <%= f.button :submit, "Add", class: "btn button-cta"%>
      </div>
            <% end %>
    </div>
  </div>
</div>

app/views/shared/flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>