config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :experiences, only: [:create, :update, :destroy]
  resources :organizations, only: [:create, :destroy]
  post 'coforg', to: 'organizations#createorfind'
  resources :applies do
    resources :organizations, only: [ :edit, :update]
    member do
      patch "/change_status", to:'applies#change_status'
      patch "/accept", to:'applies#accept'
      patch "/decline", to:'applies#decline'
    end
    resources :notification_applies, only: [:create] do
      patch "/change_read_apply", to: 'applies#change_read_apply', as: :change_apply
    end
    resources :notification_interviews, only: [:create] do
      patch "/change_read_interview", to: 'applies#change_read_interview', as: :change_int
    end
    resources :contacts, only: [:create, :update, :destroy]
    resources :interviews, only: [:create, :update, :destroy] do
      resources :reviews, only: [:create, :update, :destroy] do
        patch "/upvote", to:"reviews#upvote"
        patch "/downvote", to:"reviews#downvote"
      end
    end
  end
  resources :votes, only: [:create, :update, :destroy]
  resources :articles, only: [:index, :show]
  get 'myprofile', to: 'pages#profile', as: :profile

end

app/views/pages/profile.html.erb
<div class="container">
    <div class="profile-main-body" id="profile-page">
    
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="profile-card">
                <div class="profile-card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <% if current_user.photo.attached? %>

                   <%= cl_image_tag(current_user.photo.key,  class: "avatar-profile") %>
                    <%else %>
                   <%=  cl_image_tag("qsdgkammqm7nwczbuagw", class: "rounded-profile", width: 150) %>
                   <%end %>
                    <div class="mt-3">
                      <h4><%= current_user.first_name %> <%= current_user.last_name %> </h4>
                       <% unless current_user.linkedin_url.nil? %>
                      <a href=<%= current_user.linkedin_url %>  > <button class="btn btn-primary">Linkedin</button></a>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
             
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="profile-card-body">
                     <div>
                  <h1>My experiences</h1>
                  
                </div>
            
                  <%current_user.experiences.each do |experience| %> 
                  <% if experience.category === "work" %>
                  <div class="experience">
                    <img src=<%=experience.organization.logo%> class="avatar-large" />
                    <div class="experience-content">
                     <div class="experience-title">
                      <p> <strong><%=experience.organization.name%></strong> </p>
                      <p><small><%=experience.start_date%> to <%=experience.end_date%> </small></p>
                     </div>
                       <p><%=experience.description%></p>
                       <% unless experience.location.blank?  %>
                         <p><small><i class="fas fa-map-marker-alt"></i>  <%=experience.location.gsub(/,.*,/, ', ')%></small></p>
                       <% end %>
                    </div>
                  <div>
                   
                      <%= link_to experience_path(experience), method: :delete, class:"" do %>
                     <i class="far fa-times-circle delete-exp"></i>
                       <% end %>
                          </div>
                          </div>

                      <%end  %> 
 
                   <%end  %> 
                 
                  <hr> 
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn button-cta " data-toggle="modal" data-target="#ExperienceModal" id="addexp" >Add an Experience</a>
                    </div>
                  </div>
                </div>
              </div>



<div class="card mb-3">
                <div class="profile-card-body">
                     <div>
                  <h1>My education</h1>
                  
                </div>
            
                  <%current_user.experiences.each do |experience| %> 
                  <% if experience.category === "school" %>
   
                  <div class="experience">
                    <img src=<%=experience.organization.logo%> class="avatar-large" />
                    <div class="experience-content">
                     <div class="experience-title">
                      <p> <strong><%=experience.organization.name%></strong> </p>
                      <p><small><%=experience.start_date%> to <%=experience.end_date%> </small></p>
                     </div>
                       <p><%=experience.description%></p>
                       <% unless experience.location.blank?  %>
                         <p><small><i class="fas fa-map-marker-alt"></i>  <%=experience.location.gsub(/,.*,/, ', ')%></small></p>
                       <% end %>
                    </div>
                  <div>
                   
                      <%= link_to experience_path(experience), method: :delete, class:"" do %>
                     <i class="far fa-times-circle delete-exp"></i>
                       <% end %>
                          </div>
                          </div>

                      <%end  %> 
 
                   <%end  %> 
                 
                  <hr> 
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn button-cta " data-toggle="modal" data-target="#SchoolModal" id="addexp" >Add an Education</a>
                    </div>
                  </div>
                </div>
              </div>
              

            </div>
            
          </div>

        </div>
    </div>



    <!-- experience modal -->

    <%= render 'shared/experience_modal', experience: @experience, display_modal_exp: @display_modal_exp %>
    
    <!-- experience modal -->


    
    <!-- School modal -->

    <%= render 'shared/school_modal', experience: @experience, display_modal_school: @display_modal_school %>


    
    <!-- School modal -->


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>